kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/is2ei/conoha-api-go-client

steps:
- name: test
  image: golang
  commands:
  - go get github.com/is2ei/conoha-api-go-client/...
  - go test ./...